### PR TITLE
Reviewed responsiveness using Bootstrap class  

### LINKED ISSUE #3: CSS in large screen campers too small
In large screen campers item are too small and text is overlapping. 
Let's keep campers on 3 columns or probably better let's allow jumbotron to go bigger on larger screen.

image2

### PR DESCRIPTION
**Pull request by artitudinale1**
Improved responsiveness.
closes #3

### CODE REVIEW

**Comment by chris-alexander** [comment]
Sorry if this is a stupid question. Why do we have both `.css` files and `.scss` files? Shouldn't we use just the `.scss` files and have `gulp-sass` compile them to CSS?

**Comment by artitudinale1** [comment]
Can be. Just to be sure I commit CSS as well. At work generally we do that. It not necessary in terms that when you check out and run gulp the css will be compiled with the scss you have been checking out.

**Comment by artitudinale1** [comment]
Can't do it now but later I will update this to master so we can merge in - re update demo live and test on different devices....essential to check CSS adjustments.

**Comment by artitudinale1** [comment]
@chris-alexander  this should be good to go as well . I know css is there I'm gonna remove it when I ll wrote gulp for dist - for the moment I need that to update online demo

**Pull request merged**
