### PR TITLE
Update/alex garulli

### PR DESCRIPTION
**Pull request by artitudinale1**
I updated my image with a path

### CODE REVIEW

**Comment by chris-alexander** [comment]
Relates to #27

@artitudinale1 did you remove your profile pic from assets?
@silverwedding do you want to do the same with yours?

**Comment by artitudinale1** [comment]
@chris-alexander  image removed :)

**Comment by chris-alexander** [comment]
I think we need to merge your Readme PR first because this one seems to include those commits. There is probably a way to separate it but I think it would be easier to merge that one first for now.

**Comment by artitudinale1** [comment]
@chris-alexander  if we can merge all PR down we can actually see where we are at. Anything we go back. So I would say merge those down.

**Comment by chris-alexander** [comment]
Can you rebase from master now? Hopefully it will get rid of the unnecessary commits.

**Comment by artitudinale1** [comment]
I will - but I think you can merge it cos you merge down other branch so are there anyway.

**Pull request merged**
